version: "3.8"

services:
  redis:
    image: redis
    container_name: redis

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase

  vote:
    image: voting-app
    container_name: vote
    ports:
      - "5001:80"
    depends_on:
      - redis

  worker:
    image: worker-app
    container_name: worker
    depends_on:
      - db
      - redis

  result:
    image: result-app
    container_name: result
    ports:
      - "5002:80"
    depends_on:
      - db

